### ISSUE TITLE
require missing file in test/test_helper.rb ends with CI success(EXIT 0)

### ISSUE THREAD

**Issue by naofumi-fujii** [test-unit/test-unit-rails#18] opened 2017-08-21 06:28 UTC
i built an sample app for this issue
 https://github.com/naofumi-fujii/my-sample-rails/pull/10

it shows message like this.
```
Loaded suite RequireFailedOmissions
Started
O
================================================================================
failed to load: </home/ubuntu/my-sample-rails/test/test_helper.rb>: <cannot load such file -- non_existing_file> [test_require_home_ubuntu_my_sample_rails_test_test_helper_rb(RequireFailedOmissions)]
/home/ubuntu/my-sample-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
================================================================================


Finished in 0.005636255 seconds.
--------------------------------------------------------------------------------
1 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------
177.42 tests/s, 0.00 assertions/s
```

(not sure this is the expected behaviour,

**Comment by naofumi-fujii** [comment] 2017-08-21 06:57
this seems to be an minitest issue, closing

**Comment by naofumi-fujii** [comment] 2017-09-06 05:41
this issue was caused by test-unit-rails

**Comment by kou** [comment] 2017-09-07 14:25
How to reproduce this?

**Comment by naofumi-fujii** [comment] 2017-09-08 01:14
updated reproduce code 🙏 
https://github.com/naofumi-fujii/my-sample-rails/pull/16/files

**Comment by kou** [comment] 2017-09-13 13:47
Thanks.
test-unit marks require failure case as omission.
"Omission" isn't treated as "failure" or "error".

Should we treat the case as "failure" instead of "omission"?

**Comment by naofumi-fujii** [comment] 2017-09-13 23:15
yes, i think case would be better to be reported as failure or error

**Comment by kou** [comment] 2017-09-14 00:51
OK. Do you want to try to change to "error" from "omission"?
https://github.com/test-unit/test-unit/blob/master/lib/test/unit/collector/load.rb#L165-L199 should be changed.

**Comment by naofumi-fujii** [comment] 2017-09-14 01:24
sure!

**Comment by naofumi-fujii** [comment] 2017-09-14 03:34
i was thinking about removing these lines
https://github.com/test-unit/test-unit/blob/master/lib/test/unit/collector/load.rb#L115-L116

what do you think? @kou

**Comment by kou** [comment] 2017-09-14 04:16
Did you run with it?
With this change, all tests aren't run. Is it what you expect?

**Comment by naofumi-fujii** [comment] 2017-09-14 05:25
yes, i think raising LoadError immediately would be more clear behaviour
rather than running all tests with error inside.

**Comment by naofumi-fujii** [comment] 2017-09-14 06:01
this is sample using TestUnit with LoadError not rescued.
https://github.com/naofumi-fujii/my-sample-rails/pull/17

**Comment by kou** [comment] 2017-09-14 15:21
Umm.

You think this is better:

```text
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- non_existing_file (LoadError)
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /tmp/my-sample-rails/test/test_helper.rb:5:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:114:in `block in collect_file'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:134:in `add_load_path'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:112:in `collect_file'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:87:in `block in collect_recursive'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:85:in `each'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:85:in `collect_recursive'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:46:in `block (2 levels) in collect'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:43:in `each'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:43:in `block in collect'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:131:in `add_load_path'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/collector/load.rb:38:in `collect'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/autorunner.rb:102:in `block in <class:AutoRunner>'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/autorunner.rb:423:in `run'
	from /home/kou/.bundle/ruby/2.3.0/test-unit-7d5a7e3f094a/lib/test/unit/autorunner.rb:62:in `run'
	from /var/lib/gems/2.3.0/gems/test-unit-rails-5.1.3/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/command/base.rb:63:in `perform'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/command.rb:44:in `invoke'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/commands.rb:16:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /tmp/my-sample-rails/bin/rails:9:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `load'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `block in load'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `load'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

than:

```text
Loaded suite RequireFailedErrors
Started
E
================================================================================
Error: test_require_tmp_my_sample_rails_test_controllers_articles_controller_test_rb(RequireFailedErrors): LoadError: failed to load: </tmp/my-sample-rails/test/controllers/articles_controller_test.rb>: <cannot load such file -- non_existing_file>
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/test_helper.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/controllers/articles_controller_test.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/test-unit-rails-5.1.3/lib/rails/commands/test/test_command.rb:33:in `perform'
================================================================================
E
================================================================================
Error: test_require_tmp_my_sample_rails_test_models_article_test_rb(RequireFailedErrors): LoadError: failed to load: </tmp/my-sample-rails/test/models/article_test.rb>: <cannot load such file -- non_existing_file>
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/test_helper.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/models/article_test.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/test-unit-rails-5.1.3/lib/rails/commands/test/test_command.rb:33:in `perform'
================================================================================
E
================================================================================
Error: test_require_tmp_my_sample_rails_test_system_articles_test_rb(RequireFailedErrors): LoadError: failed to load: </tmp/my-sample-rails/test/system/articles_test.rb>: <cannot load such file -- non_existing_file>
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/test_helper.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/application_system_test_case.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/system/articles_test.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/test-unit-rails-5.1.3/lib/rails/commands/test/test_command.rb:33:in `perform'
================================================================================
E
================================================================================
Error: test_require_tmp_my_sample_rails_test_test_helper_rb(RequireFailedErrors): LoadError: failed to load: </tmp/my-sample-rails/test/test_helper.rb>: <cannot load such file -- non_existing_file>
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/tmp/my-sample-rails/test/test_helper.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/test-unit-rails-5.1.3/lib/rails/commands/test/test_command.rb:33:in `perform'
================================================================================


Finished in 0.007045119 seconds.
--------------------------------------------------------------------------------
4 tests, 0 assertions, 0 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------
567.77 tests/s, 0.00 assertions/s
```


I think that the latter is better because it shows summary at the end, suppresses needless backtraces and reports all "load failed files" by only one test run. The former needs N test runs. Because the former reports only the first load failure.

**Comment by naofumi-fujii** [comment] 2017-09-15 00:02
Oh, now i see that latter one is more clear for users.
i will try to fix that way.

**Comment by naofumi-fujii** [comment] 2017-09-15 08:13
created PR 🔬 
https://github.com/test-unit/test-unit/pull/153

**Comment by naofumi-fujii** [comment] 2017-09-15 08:24
found my mistake 🙈

**Comment by naofumi-fujii** [comment] 2017-09-17 03:01
created PR here 💡 
https://github.com/test-unit/test-unit/pull/154

**Comment by kou** [comment] 2017-09-21 05:51
Merged.

**Closed by kou** 2017-09-21 05:51 UTC
